version: '3.8'

services:

  db:
    container_name: postgresovisco
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: discord_bot
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports: 
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: esovisco@pg.edu.pl
      PGADMIN_DEFAULT_PASSWORD: 1qazaq1
    ports:
      - "5555:80"
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
