version: '3.1'

services:
  db:
    container_name: postgresovisco
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
